module.exports = {
  parser : 'babel-eslint',
  env : {
    es6 : true,
    node : true,
  },
  parserOptions : {
    sourceType : 'module',
    ecmaFeatures : {
      impliedStrict : true,
      experimentalObjectRestSpread : true,
    },
  },
  rules : {
    // possible errors
    'no-await-in-loop' : [ 'error' ],
    'no-cond-assign' : [ 'error' ],
    'no-console' : [ 'warn' ],
    'no-constant-condition' : [ 'warn' ],
    'no-control-regex' : [ 'error' ],
    'no-debugger' : [ 'error' ],
    'no-dupe-args' : [ 'error' ],
    'no-dupe-keys' : [ 'error' ],
    'no-duplicate-case' : [ 'error' ],
    'no-empty' : [ 'warn' ],
    'no-empty-character-class' : [ 'error' ],
    'no-ex-assign' : [ 'error' ],
    'no-extra-boolean-cast' : [ 'error' ],
    'no-extra-semi' : [ 'warn' ],
    'no-func-assign' : [ 'error' ],
    'no-inner-declarations' : [ 'error' ],
    'no-invalid-regexp' : [ 'error' ],
    'no-irregular-whitespace' : [ 'error' ],
    'no-obj-calls' : [ 'error' ],
    'no-regex-spaces' : [ 'warn' ],
    'no-sparse-arrays' : [ 'warn' ],
    'no-template-curly-in-string' : [ 'warn' ],
    'no-unexpected-multiline' : [ 'error' ],
    'no-unreachable' : [ 'warn' ],
    'no-unsafe-finally' : [ 'error' ],
    'no-unsafe-negation' : [ 'error' ],
    'use-isnan' : [ 'error' ],
    'valid-typeof' : [ 'error' ],

    // best practices
    'accessor-pairs' : [ 'error' ],
    'array-callback-return' : [ 'warn' ],
    'curly' : [ 'error' ],
    'default-case' : [ 'error' ],
    'dot-location' : [ 'error', 'property' ],
    'dot-notation' : [ 'error', { allowKeywords : true } ],
    'eqeqeq' : [ 'error' ],
    'guard-for-in' : [ 'error' ],
    'no-alert' : [ 'error' ],
    'no-caller' : [ 'error' ],
    'no-case-declarations' : [ 'error' ],
    'no-else-return' : [ 'error' ],
    'no-empty-pattern' : [ 'error' ],
    'no-eq-null' : [ 'error' ],
    'no-eval' : [ 'error' ],
    'no-extend-native' : [ 'error' ],
    'no-extra-bind' : [ 'warn' ],
    'no-extra-label' : [ 'error' ],
    'no-fallthrough' : [ 'error' ],
    'no-floating-decimal' : [ 'error' ],
    'no-global-assign' : [ 'error' ],
    'no-implicit-globals' : [ 'error' ],
    'no-implied-eval' : [ 'error' ],
    'no-labels' : [ 'warn', { allowLoop : true, allowSwitch : true } ],
    'no-lone-blocks' : [ 'warn' ],
    'no-loop-func' : [ 'error' ],
    'no-mixed-operators' : [ 'error' ],
    'no-multi-spaces' : [ 'error' ],
    'no-multi-str' : [ 'error' ],
    'no-native-reassign' : [ 'error' ],
    'no-negated-condition' : [ 'off' ],
    'no-new-func' : [ 'error' ],
    'no-new-wrappers' : [ 'error' ],
    'no-octal' : [ 'error' ],
    'no-octal-escape' : [ 'error' ],
    'no-param-reassign' : [ 'error' ], // in a perfect world, we would add { props : "true" }
    'no-proto' : [ 'error' ],
    'no-redeclare' : [ 'error', { builtinGlobals : true } ],
    'no-return-assign' : [ 'error' ],
    'no-script-url' : [ 'warn' ],
    'no-self-compare' : [ 'error' ],
    'no-sequences' : [ 'error' ],
    'no-sync' : [ 'warn' ],
    'no-throw-literal' : [ 'error' ],
    'no-unused-expressions' : [ 'warn' ],
    'no-useless-call' : [ 'warn' ],
    'no-useless-concat' : [ 'warn' ],
    'no-useless-escape' : [ 'error' ],
    'no-useless-return' : [ 'error' ],
    'no-void' : [ 'warn' ],
    'no-warning-comments' : [ 'warn' ],
    'no-with' : [ 'error' ],
    'radix' : [ 'warn' ],
    'wrap-iife' : [ 'error' ],

    // strict mode
    'strict' : [ 'error' ],

    // variables
    'no-catch-shadow' : [ 'error' ],
    'no-delete-var' : [ 'error' ],
    'no-label-var' : [ 'error' ],
    'no-shadow' : [ 'error' ],
    'no-shadow-restricted-names' : [ 'error' ],
    'no-undef' : [ 'error' ],
    'no-undef-init' : [ 'error' ],
    'no-unused-vars' : [ 'error', { args : 'none'} ],
    'no-use-before-define' : [ 'error', 'nofunc' ],

    // node/commonjs environment
    'callback-return' : [ 'error', [ 'callback', 'cb', 'next', 'done' ] ],
    'handle-callback-err' : [ 'warn' ],
    'no-mixed-requires' : [ 'error' ],
    'no-new-require' : [ 'error' ],
    'no-path-concat' : [ 'error' ],
    'no-process-exit' : [ 'warn' ],
    'no-restricted-modules' : [ 'error' ],

    // es6
    'arrow-parens' : [ 'error', 'always' ],
    'arrow-spacing' : [ 'error' ],
    'constructor-super' : [ 'error' ],
    'no-class-assign' : [ 'error' ],
    'no-confusing-arrow' : [ 'error' ],
    'no-const-assign' : [ 'error' ],
    'no-dupe-class-members' : [ 'error' ],
    'no-duplicate-imports' : [ 'error' ],
    'no-new-symbol' : [ 'error' ],
    'no-return-await' : [ 'error' ],
    'no-this-before-super' : [ 'error' ],
    'no-useless-computed-key' : [ 'error' ],
    'no-useless-constructor' : [ 'error' ],
    'no-useless-rename' : [ 'error' ],
    'no-var' : [ 'error' ],
    'prefer-arrow-callback' : [ 'warn' ],
    'prefer-rest-params' : [ 'warn' ],
    'prefer-spread' : [ 'warn' ],
    'rest-spread-spacing' : [ 'error', 'never' ],

    // unused
    'array-bracket-spacing' : [ 'off' ],
    'arrow-body-style' : [ 'off' ],
    'block-scoped-var' : [ 'off' ],
    'block-spacing' : [ 'off' ],
    'class-methods-use-this' : [ 'off' ],
    'complexity' : [ 'off' ],
    'computed-property-spacing' : [ 'off' ],
    'consistent-return' : [ 'off' ],
    'consistent-this' : [ 'off' ],
    'func-name-matching' : [ 'off' ],
    'func-names' : [ 'off' ],
    'func-style' : [ 'off' ],
    'generator-star-spacing' : [ 'off' ],
    'global-require' : [ 'off' ],
    'id-length' : [ 'off' ],
    'id-match' : [ 'off' ],
    'init-declarations' : [ 'off' ],
    'line-comment-position' : [ 'off' ],
    'lines-around-comment' : [ 'off' ],
    'lines-around-directive' : [ 'off' ],
    'max-depth' : [ 'off' ],
    'max-len' : [ 'off' ],
    'max-lines' : [ 'off' ],
    'max-params' : [ 'off' ],
    'max-statements' : [ 'off' ],
    'newline-after-var' : [ 'off' ],
    'newline-before-return' : [ 'off' ],
    'newline-per-chained-call' : [ 'off' ],
    'no-continue' : [ 'off' ],
    'no-div-regex' : [ 'off' ],
    'no-extra-parens' : [ 'off' ],
    'no-inline-comments' : [ 'off' ],
    'no-invalid-this' : [ 'off' ],
    'no-iterator' : [ 'off' ],
    'no-magic-numbers' : [ 'off' ],
    'no-mixed-spaces-and-tabs' : [ 'off' ],
    'no-negated-in-lhs' : [ 'off' ],
    'no-new' : [ 'off' ],
    'no-new-object' : [ 'off' ],
    'no-plusplus' : [ 'off' ],
    'no-process-env' : [ 'off' ],
    'no-prototype-builtins' : [ 'off' ],
    'no-restricted-globals' : [ 'off' ],
    'no-restricted-imports' : [ 'off' ],
    'no-restricted-properties' : [ 'off' ],
    'no-restricted-syntax' : [ 'off' ],
    'no-self-assign' : [ 'off' ],
    'no-spaced-func' : [ 'off' ],
    'no-tabs' : [ 'off' ],
    'no-ternary' : [ 'off' ],
    'no-undefined' : [ 'off' ],
    'no-underscore-dangle' : [ 'off' ],
    'no-unmodified-loop-condition' : [ 'off' ],
    'no-unused-labels' : [ 'off' ],
    'object-curly-spacing' : [ 'off' ],
    'object-property-newline' : [ 'off' ],
    'object-shorthand' : [ 'off' ],
    'one-var' : [ 'off' ],
    'one-var-declaration-per-line' : [ 'off' ],
    'operator-assignment' : [ 'off' ],
    'operator-linebreak' : [ 'off' ],
    'padded-blocks' : [ 'off' ],
    'prefer-const' : [ 'off' ],
    'prefer-numeric-literals' : [ 'off' ],
    'prefer-reflect' : [ 'off' ],
    'prefer-template' : [ 'off' ],
    'require-jsdoc' : [ 'off' ],
    'require-yield' : [ 'off' ],
    'sort-imports' : [ 'off' ],
    'sort-keys' : [ 'off' ],
    'sort-vars' : [ 'off' ],
    'space-unary-ops' : [ 'off' ],
    'symbol-description' : [ 'off' ],
    'unicode-bom' : [ 'off' ],
    'vars-on-top' : [ 'off' ],
    'yield-star-spacing' : [ 'off' ],
  }
};
