module.exports = {
  parser : 'babel-eslint',
  env : {
    es6 : true,
    node : true,
  },
  parserOptions : {
    sourceType : 'module',
    ecmaFeatures : {
      impliedStrict : true,
      experimentalObjectRestSpread : true,
    },
  },
  rules : {
    // possible errors
    'no-cond-assign' : [ 'error' ],
    'no-console' : [ 'warn' ],
    'no-constant-condition' : [ 'warn' ],
    'no-control-regex' : [ 'error' ],
    'no-debugger' : [ 'error' ],
    'no-dupe-args' : [ 'error' ],
    'no-dupe-keys' : [ 'error' ],
    'no-duplicate-case' : [ 'error' ],
    'no-empty' : [ 'warn' ],
    'no-empty-character-class' : [ 'error' ],
    'no-ex-assign' : [ 'error' ],
    'no-extra-semi' : [ 'warn' ],
    'no-func-assign' : [ 'error' ],
    'no-invalid-regexp' : [ 'error' ],
    'no-irregular-whitespace' : [ 'error' ],
    'no-obj-calls' : [ 'error' ],
    'no-regex-spaces' : [ 'warn' ],
    'no-sparse-arrays' : [ 'warn' ],
    'no-unexpected-multiline' : [ 'error' ],
    'no-unreachable' : [ 'warn' ],
    'no-unsafe-finally' : [ 'error' ],
    'use-isnan' : [ 'error' ],
    'valid-jsdoc' : [ 'warn' ],
    'valid-typeof' : [ 'error' ],

    // best practices
    'accessor-pairs' : [ 'error' ],
    'array-callback-return' : [ 'warn' ],
    'curly' : [ 'error' ],
    'default-case' : [ 'error' ],
    'dot-location' : [ 'error', 'property' ],
    'dot-notation' : [ 'error', { allowKeywords : true } ],
    'eqeqeq' : [ 'error' ],
    'guard-for-in' : [ 'error' ],
    'no-alert' : [ 'error' ],
    'no-caller' : [ 'error' ],
    'no-case-declarations' : [ 'error' ],
    'no-else-return' : [ 'error' ],
    'no-empty-pattern' : [ 'error' ],
    'no-eq-null' : [ 'error' ],
    'no-extend-native' : [ 'error' ],
    'no-extra-bind' : [ 'warn' ],
    'no-extra-label' : [ 'error' ],
    'no-fallthrough' : [ 'error' ],
    'no-floating-decimal' : [ 'error' ],
    'no-implicit-coercion' : [ 'error' ],
    'no-implicit-globals' : [ 'error' ],
    'no-implied-eval' : [ 'error' ],
    'no-invalid-this' : [ 'error' ],
    'no-labels' : [ 'warn', { allowLoop : true, allowSwitch : true } ],
    'no-lone-blocks' : [ 'warn' ],
    'no-loop-func' : [ 'error' ],
    'no-multi-spaces' : [ 'error' ],
    'no-multi-str' : [ 'error' ],
    'no-native-reassign' : [ 'error' ],
    'no-new-func' : [ 'error' ],
    'no-new-wrappers' : [ 'error' ],
    'no-octal' : [ 'error' ],
    'no-octal-escape' : [ 'error' ],
    'no-param-reassign' : [ 'error' ], // in a perfect world, we would add { props : "true" }
    'no-proto' : [ 'error' ],
    'no-redeclare' : [ 'error', { builtinGlobals : true } ],
    'no-return-assign' : [ 'error' ],
    'no-script-url' : [ 'warn' ],
    'no-self-compare' : [ 'error' ],
    'no-sequences' : [ 'error' ],
    'no-throw-literal' : [ 'error' ],
    'no-unused-expressions' : [ 'warn' ],
    'no-useless-call' : [ 'warn' ],
    'no-useless-concat' : [ 'warn' ],
    'no-void' : [ 'warn' ],
    'no-with' : [ 'error' ],
    'radix' : [ 'warn' ],
    'wrap-iife' : [ 'error' ],

    // strict mode
    'strict' : [ 'error' ],

    // variables
    'no-catch-shadow' : [ 'error' ],
    'no-delete-var' : [ 'error' ],
    'no-label-var' : [ 'error' ],
    'no-shadow' : [ 'error' ],
    'no-shadow-restricted-names' : [ 'error' ],
    'no-undef' : [ 'error' ],
    'no-undef-init' : [ 'error' ],
    'no-unused-vars' : [ 'error', { args : 'none'} ],
    'no-use-before-define' : [ 'error', 'nofunc' ],

    // node/commonjs environment
    'callback-return' : [ 'error', [ 'callback', 'cb', 'next', 'done' ] ],
    'handle-callback-err' : [ 'warn' ],
    'no-mixed-requires' : [ 'error' ],
    'no-new-require' : [ 'error' ],
    'no-path-concat' : [ 'error' ],
    'no-process-exit' : [ 'warn' ],
    'no-restricted-modules' : [ 'error' ],

    // es6
    // 'arrow-parens': [ 'error', 'always' ], // @todo this causes issues for async arrow functions
    'arrow-spacing' : [ 'error' ],
    'constructor-super' : [ 'error' ],
    'no-class-assign' : [ 'error' ],
    'no-confusing-arrow' : [ 'error' ],
    'no-const-assign' : [ 'error' ],
    'no-dupe-class-members' : [ 'error' ],
    'no-duplicate-imports' : [ 'error' ],
    'no-new-symbol' : [ 'error' ],
    'no-this-before-super' : [ 'error' ],
    'no-useless-constructor' : [ 'error' ],
    'no-var' : [ 'error' ],
    'prefer-arrow-callback' : [ 'warn' ],
    'prefer-rest-params' : [ 'warn' ],
    'prefer-spread' : [ 'warn' ],
  }
};
