const TAB_WIDTH = 2;

module.exports = {
  plugins : [ 'react' ],
  parserOptions : {
    sourceType : 'module',
    ecmaFeatures : {
      jsx : true,
    },
  },
  rules : {
    'react/default-props-match-prop-types' : [ 'warn' ],
    'react/display-name' : [ 'error' ],
    'react/forbid-foreign-prop-types' : [ 'warn' ],
    'react/no-array-index-key' : [ 'warn' ],
    'react/no-children-prop' : [ 'error' ],
    'react/no-danger' : [ 'error' ],
    'react/no-danger-with-children' : [ 'error' ],
    'react/no-deprecated' : [ 'error' ],
    'react/no-did-mount-set-state' : [ 'error' ],
    'react/no-did-update-set-state' : [ 'error' ],
    'react/no-direct-mutation-state' : [ 'error' ],
    'react/no-find-dom-node' : [ 'error' ],
    'react/no-is-mounted' : [ 'error' ],
    'react/no-redundant-should-component-update' : [ 'warn' ],
    'react/no-render-return-value' : [ 'error' ],
    'react/no-string-refs' : [ 'warn' ],
    'react/no-unescaped-entities' : [ 'error' ],
    'react/no-unknown-property' : [ 'error' ],
    'react/no-will-update-set-state' : [ 'error' ],
    'react/prefer-es6-class' : [ 'error' ],
    'react/react-in-jsx-scope' : [ 'error' ],
    'react/require-render-return' : [ 'error' ],
    'react/self-closing-comp' : [ 'error' ],
    'react/style-prop-object' : [ 'error' ],
    'react/void-dom-elements-no-children' : [ 'error' ],
    'react/jsx-key' : [ 'warn' ],
    'react/jsx-no-comment-textnodes' : [ 'error' ],
    'react/jsx-no-duplicate-props' : [ 'warn', { ignoreCase : true } ],
    'react/jsx-no-target-blank' : [ 'error' ],
    'react/jsx-no-undef' : [ 'error' ],
    'react/jsx-pascal-case' : [ 'error' ],
    'react/jsx-uses-react' : [ 'error' ],
    'react/jsx-uses-vars' : [ 'error' ],

    'react/forbid-component-props' : [ 'off' ],
    'react/forbid-elements' : [ 'off' ],
    'react/jsx-filename-extension' : [ 'off' ],
    'react/jsx-no-literals' : [ 'off' ],
    'react/jsx-sort-props' : [ 'off' ],
    'react/no-comment-textnodes' : [ 'off' ],
    'react/no-multi-comp' : [ 'off' ],
    'react/no-set-state' : [ 'off' ],
    'react/no-unused-prop-types' : [ 'off' ],
    'react/require-extension' : [ 'off' ],
    'react/sort-comp' : [ 'off' ],
    'react/sort-prop-types' : [ 'off' ],
    'react/wrap-multilines' : [ 'off' ],
  },
};
