const TAB_WIDTH = 2;

module.exports = {
  rules : {
    // style
    'brace-style' : [ 'error', '1tbs' ],
    'camelcase' : [ 'error', { properties : 'never' } ],
    'comma-dangle' : [ 'error', 'always-multiline' ],
    'comma-spacing' : [ 'error', { before : false, after : true } ],
    'comma-style' : [ 'error' ],
    'eol-last' : [ 'error' ],
    'func-call-spacing' : [ 'error', 'never' ],
    'id-blacklist' : [ 'error', 'data' ],
    'indent' : [ 'error', TAB_WIDTH, { SwitchCase : 1 } ],
    'jsx-quotes' : [ 'error', 'prefer-single' ],
    'key-spacing' : [ 'error', { beforeColon : true, afterColon : true } ],
    'keyword-spacing' : [ 'error' ],
    'linebreak-style' : [ 'error', 'unix' ],
    'max-nested-callbacks' : [ 'warn', 3 ],
    'max-statements-per-line' : [ 'error', { max : 1 } ],
    'multiline-ternary' : [ 'error', 'never' ],
    'new-cap' : [ 'warn', { capIsNew : false } ],
    'new-parens' : [ 'error' ],
    'no-array-constructor' : [ 'error' ],
    'no-bitwise' : [ 'error' ],
    'no-empty-function' : [ 'warn' ],
    'no-lonely-if' : [ 'error' ],
    'no-multiple-empty-lines' : [ 'error' ],
    'no-nested-ternary' : [ 'error' ],
    'no-trailing-spaces' : [ 'error' ],
    'no-unneeded-ternary' : [ 'error' ],
    'no-whitespace-before-property' : [ 'error' ],
    'quote-props' : [ 'error', 'consistent-as-needed' ],
    'quotes' : [ 'error', 'single', { avoidEscape : true, allowTemplateLiterals : true } ],
    'semi' : [ 'error', 'always' ],
    'semi-spacing' : [ 'error' ],
    'space-before-blocks' : [ 'error', 'always' ],
    'space-before-function-paren' : [ 'error', { anonymous : 'never', named : 'never', asyncArrow : 'always' } ],
    'space-in-parens' : [ 'error' ],
    'space-infix-ops' : [ 'error' ],
    'spaced-comment' : [ 'error' ],
    'template-curly-spacing' : [ 'error', 'never' ],
    'wrap-regex' : [ 'error' ],
    'yoda' : [ 'error', 'never' ],
  },
};
